summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-32-aarch64/releases/download/2025.01.29/libfontconfig-2.15.0-android-32-arm64-v8a.release.tar.xz
bin-sha: 55bf3952716095a4a3a28c16e5df332d8b2cd1ce20cc5e7faf81b2ac24964f27
